# Generated by Django 4.0.4 on 2022-04-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Тема')),
                ('full_text', models.TextField(verbose_name='Текст вопроса')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
