# Generated by Django 4.0.4 on 2022-04-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiles',
            options={'verbose_name': 'Доска', 'verbose_name_plural': 'Доски'},
        ),
        migrations.AddField(
            model_name='artiles',
            name='comp',
            field=models.BooleanField(default=False, verbose_name='Решенный'),
        ),
        migrations.AddField(
            model_name='artiles',
            name='rang',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
    ]
