# Generated by Django 4.0.4 on 2022-04-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_artiles_user_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
