# Generated by Django 4.0.4 on 2022-04-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_artiles_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='que',
        ),
        migrations.AlterModelTable(
            name='artiles',
            table='que',
        ),
    ]
